name: Download FIB Files
inputs:
  fib_file:
    required: true
runs:
  using: "composite"
  steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: ${{ inputs.fib_file }}
    - name: Download DSI Studio
      run: |
        curl -sSLO "https://github.com/frankyeh/DSI-Studio/releases/download/2021.12.03/dsi_studio_ubuntu_2004.zip"
        unzip -q *.zip
        rm *.zip
      shell: bash
