name: Auto-Track (URL)

on: 
  workflow_dispatch:
    inputs:
      fib_url:
        description: 'URL to the fib file'
        required: true
jobs:    
  check_url:
    runs-on: ubuntu-latest
    steps:
      - name: Check If URL is active
        run: |
          curl -sSf ${{ github.event.inputs.fib_url }} -o /dev/null 
  automated_tracking:
    needs: check_url
    strategy:
      matrix:
        tracts: [Arcuate_Fasciculus_L,Arcuate_Fasciculus_R,Cingulum_Frontal,Cingulum_Par,Inferior_Fronto_Occipital_Fasciculus,Inferior_Longitudinal_Fasciculus,Superior_Longitudinal_Fasciculus1,Superior_Longitudinal_Fasciculus2,Superior_Longitudinal_Fasciculus3,"Uncinate,Vertical,Fornix,Aslant",Corticospinal,Corticostriatal_Tract_Anterior,Thalamic_Radiation_Anterior,Optic_Radiation_L,Optic_Radiation_R,Corpus_Callosum_Forceps_Minor,Corpus_Callosum_Body,Corpus_Callosum_Forceps_Major]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Download DSI Studio and FIB file
        run: |
          echo "Download ${{ github.event.inputs.fib_url }}"
          curl -sSLOf ${{ github.event.inputs.fib_url }}
          curl -sSLO "https://github.com/frankyeh/DSI-Studio/releases/download/2021.12.03/dsi_studio_ubuntu_2004.zip"  
          unzip -q *.zip
          rm *.zip
          chmod 777 ./dsi-studio/dsi_studio
      - name: Tracking
        run: |
          ./dsi-studio/dsi_studio --action=atk --source=*.fib.gz --track_id=${{ matrix.tracts }}
          mv ./**/*.tt.gz .
          mv ./**/*.stat.txt .
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: tractography
          path: |
            ./*.tt.gz 
            ./*.stat.txt 
          if-no-files-found: error
          retention-days: 90
