name: Auto-Track (OpenNeuro)

on: 
  workflow_dispatch:
    inputs:
      id:
        description: 'OpenNeuro ID'
        default: ds001021
        required: true
      tract:
        description: "Tract of Interests. Full list at https://github.com/frankyeh/DSI-Studio-atlas/blob/main/ICBM152/ICBM152.tt.gz.txt"
        default: "Arcuate,Optic_Radiation"
        required: true
      save_src:
        type: boolean
        required: true
        default: 'false'
        description: Save SRC Files
        
jobs:    
  openneuro_download:
    runs-on: ubuntu-18.04
    outputs:
      files: ${{ steps.fib.outputs.files }}
    steps:
      - name: Download OpenNeuro
        run: |
          aws s3 sync --no-sign-request --exclude "*" --include "*dwi.*" s3://openneuro.org/${{ github.event.inputs.id }} ${{ github.event.inputs.id }}
          ls * -l    
      - name: Download DSI Studio
        run: |
          curl -sL "https://github.com/frankyeh/DSI-Studio/releases/download/2021.12.03/dsi_studio_ubuntu_1804.zip" | jar x
          chmod 777 ./dsi-studio/dsi_studio
      - name: Create SRC Files
        run: |
          ./dsi-studio/dsi_studio --action=src --source=${{ github.event.inputs.id }}
          mv ./**/*.src.gz .
          ./dsi-studio/dsi_studio --action=rec --source=*.src.gz --save_src=*.src.gz
      - name: Upload SRC files
        uses: actions/upload-artifact@v2.2.4
        if: ${{ github.event.inputs.save_src == 'true' }}
        with:
          name: src files
          path: ./*.src.gz
          if-no-files-found: error
          retention-days: 90
      - name: Create FIB Files
        id: fib
        run: |          
          ./dsi-studio/dsi_studio --action=rec --source=*.src.gz
          FIB_LIST=$(ls *.fib.gz | jq -R -s -c 'split("\n")[:-1]')
          echo ::set-output name=files::${FIB_LIST}
      - name: Upload FIB files
        uses: actions/upload-artifact@v2.2.4
        with:
          name: fib files
          path: ./*.fib.gz
          if-no-files-found: error
          retention-days: 90

        
  automated_tracking:
    needs: openneuro_download
    strategy:
      matrix:
        files: ${{ fromjson(needs.openneuro_download.outputs.files) }}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: fib files
      - name: Download DSI Studio
        run: |
          curl -sSLO "https://github.com/frankyeh/DSI-Studio/releases/download/2021.12.03/dsi_studio_ubuntu_2004.zip"
          unzip -q *.zip
          rm *.zip
          chmod 777 ./dsi-studio/dsi_studio
      - name: Tracking
        run: |
          ./dsi-studio/dsi_studio --action=atk --source=${{ matrix.tracts }} --track_id=${{ github.event.inputs.tract }}
          mv ./**/*.tt.gz .
          mv ./**/*.stat.txt .
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: tractography
          path: |
            ./*.tt.gz 
            ./*.stat.txt 
          if-no-files-found: error
          retention-days: 90
