name: DSI Studio Cloud

on: [push]

  
jobs:
  automated_tracking:
    runs-on: macos-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Download DSI Studio
        run: |
          curl -sSLO https://github.com/frankyeh/DSI-Studio/releases/download/2021.10.05/dsi_studio_mac.zip
          unzip dsi_studio_mac.zip
          echo "$PWD/dsi_studio.app/Contents/MacOS/" >> $GITHUB_PATH
      - name: Download Data
        run: |
          mkdir data
          cd data
          curl -sSLO https://www.dropbox.com/s/kz88gt5vrpi0dvr/100206.src.gz
          cd ..
      - name: Tracking
        run: |
          cd data
          ls -l
          sudo dsi_studio --action=rec --source=100206.src.gz --cmd="[Step T2][Edit][Rotate to MNI2]"
          sudo dsi_studio --action=atk --source=*.fib.gz
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: result
          path: data
          if-no-files-found: error
          retention-days: 90
