name: DSI Studio Cloud
on: 
  workflow_dispatch:
    inputs:
      id:
        description: 'OpenNeuro Accession Number'
        default: ds001021
        required: true
      eddy:
        type: boolean
        default: true
        description: 'Preprocessing: Eddy correction'
      region_analysis:
        type: boolean
        default: true
        description: 'Pipeline: Region Analysis'
      connectivity_matrix:
        type: boolean
        default: true
        description: 'Pipeline: Connectivity Matrix'
      autotrack:
        type: boolean
        default: true
        description: 'Pipeline: Automatic Fiber Tracking'
      atlas:
        description: 'Options: Atlases'
        default: 'HCP-MMP,FreeSurferDKT_Cortical'
        required: false
      tract:
        description: 'Options: Tracts of Interest'
        default: 'Arcuate_Fasciculus_L,Optic_Radiation_L'
        required: false
      
jobs:    
  download_data:
    runs-on: ubuntu-18.04
    outputs:
      files: ${{ steps.src.outputs.files }}
    steps:
      - name: Download ${{ github.event.inputs.id }}
        run: |
          aws s3 sync --no-sign-request --exclude "*" --include "*dwi.*" s3://openneuro.org/${{ github.event.inputs.id }} ${{ github.event.inputs.id }}
          ls * -l    
      - name: Download DSI Studio
        run: |
          curl -sL "https://github.com/frankyeh/DSI-Studio/releases/download/2021.12.03/dsi_studio_ubuntu_1804.zip" | jar x
          chmod 777 ./dsi-studio/dsi_studio
          
      - name: Create SRC Files
        id: src
        run: |
          ./dsi-studio/dsi_studio --action=src --source=${{ github.event.inputs.id }}
          mv ./**/*.src.gz .
          ./dsi-studio/dsi_studio --action=qc --source=.
          FIB_LIST=$(ls *.src.gz | jq -R -s -c 'split("\n")[:-1]')
          echo ::set-output name=files::${FIB_LIST}    
      
      - name: Upload SRC QC report
        uses: actions/upload-artifact@v2.2.4
        with:
          name: openneuro_${{ github.event.inputs.id }}_raw_qc
          path: ./qc.txt
          if-no-files-found: error
          retention-days: 90

      - name: Upload SRC files for Eddy
        if: ${{ github.event.inputs.eddy }}
        uses: actions/upload-artifact@v2.2.4
        with:
          name: openneuro_${{ github.event.inputs.id }}_raw_src
          path: ./*.src.gz
          if-no-files-found: error
          retention-days: 90

      - name: Upload SRC files Skipping Eddy
        if: ${{ !github.event.inputs.eddy }}
        uses: actions/upload-artifact@v2.2.4
        with:
          name: openneuro_${{ github.event.inputs.id }}_src
          path: ./*.src.gz
          if-no-files-found: error
          retention-days: 90


  preprocessing:
    needs: download_data
    strategy:
      matrix:
        files: ${{ fromjson(needs.download_data.outputs.files) }}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Setup Environment
        if: ${{ github.event.inputs.eddy }}
        uses: ./.github/workflows/download_fib
        with:
          fib_file: openneuro_${{ github.event.inputs.id }}_raw_src
          
      - name: Setup and run Eddy
        if: ${{ github.event.inputs.eddy }}
        run: |
          curl -sSL https://fsl.fmrib.ox.ac.uk/fsldownloads/fsl-6.0.4-centos7_64.tar.gz | tar zxv --no-same-owner -C /opt fsl/bin/eddy_openmp
          export OS="Linux"
          export FSLDIR="/opt/fsl"
          export FSL_DIR="$FSLDIR"
          export FSLOUTPUTTYPE="NIFTI_GZ"
          export FSLMULTIFILEQUIT="TRUE"
          export LD_LIBRARY_PATH="$FSLDIR/lib:$LD_LIBRARY_PATH"
          export FSLTCLSH="/usr/bin/tclsh"
          export FSLWISH="/usr/bin/wish"
          export PATH="$FSLDIR/bin:$PATH"
          ./dsi-studio/dsi_studio --action=rec --source=${{ matrix.files }} --cmd="[Step T2][Corrections][EDDY]" --save_src=${{ matrix.files }}
          
      - name: Upload a Build Artifact
        if: ${{ github.event.inputs.eddy }}
        uses: actions/upload-artifact@v2.2.4
        with:
          name: openneuro_${{ github.event.inputs.id }}_src
          path: |
            ./*.src.gz
          if-no-files-found: error
          retention-days: 90        

  reconstruction:
    needs: preprocessing
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.fib.outputs.files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Setup Environment
        uses: ./.github/workflows/download_fib
        with:
          fib_file: openneuro_${{ github.event.inputs.id }}_src
          
      - name: Create FIB Files
        id: fib
        run: |        
          ./dsi-studio/dsi_studio --action=qc --source=.
          ./dsi-studio/dsi_studio --action=rec --source=*.src.gz --mask=1 --check_btable=0  
          FIB_LIST=$(ls *.fib.gz | jq -R -s -c 'split("\n")[:-1]')
          echo ::set-output name=files::${FIB_LIST}

      - name: Upload SRC QC report
        uses: actions/upload-artifact@v2.2.4
        with:
          name: openneuro_${{ github.event.inputs.id }}_src_qc
          path: ./qc.txt
          if-no-files-found: error
          retention-days: 90
          
      - name: Upload FIB files
        uses: actions/upload-artifact@v2.2.4
        with:
          name: openneuro_${{ github.event.inputs.id }}_fib
          path: ./*.fib.gz
          if-no-files-found: error
          retention-days: 90
          
  region_analysis:
    if: ${{ github.event.inputs.region_analysis }}
    needs: reconstruction
    strategy:
      matrix:
        files: ${{ fromjson(needs.reconstruction.outputs.files) }}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Setup Environment
        uses: ./.github/workflows/download_fib
        with:
          fib_file: openneuro_${{ github.event.inputs.id }}_fib
          
      - name: Analyzing Regions
        run: |
          ./dsi-studio/dsi_studio --action=ana --source=${{ matrix.files }} --atlas=${{ github.event.inputs.atlas }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: openneuro_${{ github.event.inputs.id }}_region_analysis
          path: |
            ./*.txt 
          if-no-files-found: error
          retention-days: 90        
        
  automatic_fiber_tracking:
    if: ${{ github.event.inputs.autotrack }}
    needs: reconstruction
    strategy:
      matrix:
        files: ${{ fromjson(needs.reconstruction.outputs.files) }}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Setup Environment
        uses: ./.github/workflows/download_fib
        with:
          fib_file: openneuro_${{ github.event.inputs.id }}_fib

      - name: AutoTrack
        run: |
          ./dsi-studio/dsi_studio --action=atk --source=${{ matrix.files }} --track_id=${{ github.event.inputs.tract }}
          mv ./**/*.tt.gz .
          mv ./**/*.stat.txt .
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: openneuro_${{ github.event.inputs.id }}_autotrack
          path: |
            ./*.tt.gz 
            ./*.stat.txt 
          if-no-files-found: error
          retention-days: 90
          
  connectivity_matrix:
    if: ${{ github.event.inputs.connectivity_matrix }}
    needs: reconstruction
    strategy:
      matrix:
        files: ${{ fromjson(needs.reconstruction.outputs.files) }}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Setup Environment
        uses: ./.github/workflows/download_fib
        with:
          fib_file: openneuro_${{ github.event.inputs.id }}_fib
          
      - name: Tracking
        run: |
          ./dsi-studio/dsi_studio --action=trk --source=${{ matrix.files }} --fiber_count=1000000 --output=no_file --connectivity=${{ github.event.inputs.atlas }}
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: openneuro_${{ github.event.inputs.id }}_connectivity_matrix
          path: |
            ./*.mat
            ./*.txt
          if-no-files-found: error
          retention-days: 90
