name: Automated fiber tracking

on: 
  workflow_dispatch:
    inputs:
      fib_url:
        description: 'URL to the fib file'
        required: true
jobs:    
  automated_tracking:
    strategy:
      matrix:
        tracts: [Arcuate_Fasciculus_L,Arcuate_Fasciculus_R,Cingulum_Frontal,Cingulum_Par,Aslant,Inferior_Fronto_Occipital_Fasciculus,Inferior_Longitudinal_Fasciculus,Superior_Longitudinal_Fasciculus,"Uncinate,Vertical",Corticospinal,Corticostriatal,Thalamic_Radiation_Anterior,Thalamic_Radiation_Posterior,Thalamic_Radiation_Superior,Fornix,Optic_Radiation,Corpus_Callosum_Forceps_Minor,Corpus_Callosum_Body,Corpus_Callosum_Tapetum,Corpus_Callosum_Forceps_Major]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Download DSI Studio and FIB file
        run: |
          curl -sSLO ${{ github.event.inputs.fib_url }}
          curl -sSLO "https://github.com/frankyeh/DSI-Studio/releases/download/2021.12.03/dsi_studio_ubuntu_2004.zip"  
          unzip *.zip
          rm *.zip
          chmod 777 ./dsi-studio/dsi_studio
      - name: Tracking
        run: |
          ./dsi-studio/dsi_studio --action=atk --source=*.fib.gz --track_id=${{ matrix.tracts }}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: tractography
          path: ./**/*.tt.gz
          if-no-files-found: error
          retention-days: 90
